animations {

    enabled = true

    bezier = ease,0.25,1,0.5,1

    animation = windows,1,5,ease
    animation = windowsOut,1,5,ease
    animation = border,1,10,ease
    animation = fade,1,5,ease
    animation = workspaces,1,5,ease
}