# ==========================================================
# YashJodon-Dots
# Keybindings
# ==========================================================

# ----------------------------------------------------------
# Applications
# ----------------------------------------------------------

bind = $mod, Return, exec, $terminal
bind = $mod, D, exec, $menu
bind = $mod, E, exec, $fileManager
bind = $mod, B, exec, $browser
bind = $mod, L, exec, $lock

# ----------------------------------------------------------
# Hyprland
# ----------------------------------------------------------

bind = $mod SHIFT, R, exec, hyprctl reload
bind = $mod SHIFT, E, exit

# ----------------------------------------------------------
# Window Actions
# ----------------------------------------------------------

bind = $mod, Q, killactive
bind = $mod, F, fullscreen
bind = $mod SHIFT, F, togglefloating
bind = $mod, P, pseudo
bind = $mod, J, togglesplit

# ----------------------------------------------------------
# Move Focus
# ----------------------------------------------------------

bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r

# ----------------------------------------------------------
# Move Window
# ----------------------------------------------------------

bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, L, movewindow, r

# ----------------------------------------------------------
# Resize Window
# ----------------------------------------------------------

binde = $mod CTRL, H, resizeactive, -40 0
binde = $mod CTRL, L, resizeactive, 40 0
binde = $mod CTRL, K, resizeactive, 0 -40
binde = $mod CTRL, J, resizeactive, 0 40

# ----------------------------------------------------------
# Workspace
# ----------------------------------------------------------

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# ----------------------------------------------------------
# Move Window To Workspace
# ----------------------------------------------------------

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# ----------------------------------------------------------
# Mouse
# ----------------------------------------------------------

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# ----------------------------------------------------------
# Screenshot
# ----------------------------------------------------------

bind = , Print, exec, grimblast copy area

# ----------------------------------------------------------
# Clipboard
# ----------------------------------------------------------

bind = $mod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy