# ==========================================================
# YashJodon-Dots
# Hyprland Configuration
# ==========================================================

# Core
source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/theme.conf