# ==========================================================
# Variables
# ==========================================================

# Applications
$terminal = kitty
$fileManager = dolphin
$browser = firefox
$menu = rofi -show drun
$editor = code

# Main Modifier
$mod = SUPER

# Screenshot
$screenshot = grimblast copy area

# Lock
$lock = hyprlock

# Wallpaper
$wallpaper = swww img

# Logout Menu
$powermenu = ~/.config/hypr/scripts/power-menu.sh