# ==========================================================
# Fonts
# ==========================================================

FONT="JetBrainsMono Nerd Font"

TERMINAL_SIZE=11

UI_SIZE=11

TITLE_SIZE=12