# ==========================================================
# Keyboard Shortcuts
# ==========================================================

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+t new_tab
map ctrl+shift+w close_tab

map ctrl+shift+enter new_window

map ctrl+shift+equal increase_font_size
map ctrl+shift+minus decrease_font_size
map ctrl+shift+backspace restore_font_size

map ctrl+shift+left previous_tab
map ctrl+shift+right next_tab