# ==========================================================
# YashJodon-Dots
# Kitty Configuration
# ==========================================================

include theme.conf
include keybindings.conf

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11

# Window
window_padding_width 10
confirm_os_window_close 0

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Scrollback
scrollback_lines 10000

# Performance
enable_audio_bell no
visual_bell_duration 0
remember_window_size no
sync_to_monitor yes

# Mouse
copy_on_select yes
strip_trailing_spaces smart

# Misc
shell_integration enabled
hide_window_decorations no