# ==========================================================
# YashJodon-Dots Theme
# ==========================================================

background #181A1F
foreground #F5F7FA
selection_background #4FA3FF
selection_foreground #181A1F

cursor #4FD1C5
cursor_text_color background

color0  #181A1F
color1  #E05D5D
color2  #4CAF50
color3  #F4C430
color4  #4FA3FF
color5  #8B7CFF
color6  #4FD1C5
color7  #F5F7FA

color8  #323844
color9  #FF7B72
color10 #6BCB77
color11 #FFD166
color12 #67B4FF
color13 #A78BFA
color14 #67E8F9
color15 #FFFFFF